adminapp/urls.py
from django.contrib import admin
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path(
        "users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="user_update"
    ),
    path(
        "users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="user_delete"
    ),
    path("categories/create/", adminapp.category_create, name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/", adminapp.category_update, name="category_update"
    ),
    path(
        "categories/delete/<int:pk>/", adminapp.category_delete, name="category_delete"
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="product_create",
    ),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path(
        "products/read/<int:pk>/",
        adminapp.ProductDetailView.as_view(),
        name="product_read",
    ),
    path(
        "products/update/<int:pk>/",
        adminapp.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/delete/<int:pk>/",
        adminapp.ProductDeleteView.as_view(),
        name="product_delete",
    ),
]

authapp/urls.py
from django.urls import path, re_path

from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("change_password/", views.change_password, name="change_password"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", views.verify, name="verify"
    ),
]

basketapp/urls.py
from django.urls import path

from . import views

app_name = "basketapp"

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id>/", views.add, name="add"),
    path("remove/<int:basket_item_id>/", views.remove, name="remove"),
    path("edit/<int:basket_item_id>/<int:quantity>/", views.edit, name="edit"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin_staff/", include("adminapp.urls", namespace="admin_staff")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include("ordersapp.urls", namespace="orders"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"

urlpatterns = [
    path("", views.products, name="all"),
    path("<int:category_id>", views.category, name="category"),
    path("<int:category_id>/<int:page>", views.category, name="paged_category"),
    path("product/<int:product_id>", views.product, name="product"),
]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

from . import views

app_name = "ordersapp"

urlpatterns = [
    path("", ordersapp.OrderList.as_view(), name="orders_list"),
    path("forming/complete/<int:pk>/", ordersapp.order_forming_complete, name="order_forming_complete"),
    path("create/", ordersapp.OrderCreate.as_view(), name="order_create"),
    path("read/<int:pk>/", ordersapp.OrderRead.as_view(), name="order_read"),
    path("update/<int:pk>/", ordersapp.OrderUpdate.as_view(), name="order_update"),
    path("delete/<int:pk>/", ordersapp.OrderDelete.as_view(), name="order_delete"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=100)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name="активна", default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя", max_length=100)
    price = models.DecimalField(
        verbose_name="цена", max_digits=7, decimal_places=2, default=0
    )
    color = models.TextField(verbose_name="цвет", blank=True)
    description = models.TextField(verbose_name="описание", blank=True)
    image = models.ImageField(verbose_name="картинка", blank=True, upload_to="products")
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)
    is_active = models.BooleanField(verbose_name="активен", default=True)

    def __str__(self):
        return self.name

mainapp/views.py
import random

from django.core.paginator import EmptyPage, Paginator
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .models import Product, ProductCategory


def index(reqest):
    products = Product.objects.all()[:4]
    return render(
        reqest,
        "mainapp/index.html",
        context={
            "current_year": timezone.now().year,
            "title": "Главная",
            "products": products,
        },
    )


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def products(reqest):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product()
    return render(
        reqest,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "products": products.exclude(pk=hot_product.pk)[:4],
            "categories": categories,
            "hot_product": hot_product,
        },
    )


def category(reqest, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=category_id)
    products = Product.objects.filter(category=category)

    paginator = Paginator(products, 3)
    try:
        products_page = paginator.page(page)
    except:
        products_page = paginator.page(paginator.num_pages)

    return render(
        reqest,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "products": products_page,
            "paginator": paginator,
            "page": products_page,
            "categories": categories,
            "category": category,
            "hot_product": get_hot_product(),
        },
    )


def product(reqest, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(
        reqest,
        "mainapp/product.html",
        context={
            "title": "Продукты",
            "product": product,
            "categories": categories,
        },
    )


def contact(reqest):
    return render(
        reqest,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
        },
    )

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:all' %}"
            class="{% if request.resolver_match.view_name == 'products:all' %} active {% endif %}"
        >все</a></li>
        {% for category in categories %}
            {% if category.is_active %}
        <li><a href="{% url 'products:category' category.id %}"
             class="{% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.category_id == category.id %}" 
              active
              {% endif%}"
              > {{ category.name }}</a></li>
              {% endif %}
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="/" class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li>
        <a href="{% url link.url %}"
           {% if request.resolver_match.view_name in link.active %}
           class="active"
           {% endif %}
        >
            {{ link.name }}
        </a>
    </li>
    {% endfor %}

        <li><a href='#' class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Пользователь</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                {% if user.is_authenticated %}
                <li class="dropdown-item">
                    <a href="{% url 'auth:edit' %}">
                        <i class="fa fa-user">   {{ user.first_name|default:'Пользователь' }}</i>
                    </a>
                </li>
                 <li class="dropdown-item">
                    <a href="{% url 'orders:orders_list' %}">
                        <i class="fa fa-user"> Заказы </i>
                    </a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                <li class="dropdown-item">
                    <a href="{% url 'adminapp:users' %}">
                        Aдминка
                    </a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="dropdown-item">
                    <a href="{% url 'basket:view' %}">
                        <i class="fa fa-shopping-basket fa-1x"></i>
                        {{ user.basket.total_cost }} руб. {% if user.basket.total_quantity %} ({{ user.basket.total_quantity }}) {%endif%}
                    </a>
                </li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">выйти</a>
                    {% else %}
                    <a href="{% url 'auth:login' %}">войти</a>
                    {% endif %}
                </li>

</ul>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

mainapp/templates/mainapp/includes/inc_products.html
{% load static %}

{% if paginator %}
	
	{% if page.has_previous %}
		<a href="{% url 'products:paged_category' category.id page.previous_page_number %}">Назад</a>
	{% endif %}

		Страница {{ page.number }} из {{ paginator.num_pages }}
	
	{% if page.has_next %}
		<a href="{% url 'products:paged_category' category.id page.next_page_number %}">Вперед</a>
	{% endif %}
{% endif%}
{% for product in products %}
			<div class="block">
				<a href="{% url 'products:product' product.id %}"><img src="/media/{{ product.image }}" alt="">
					<div class="text">
						<img src="{% static "img/icon-hover.png" %}" alt="img">
						<h4>{{ product.name }}</h4>
						<br />
						<h2>{{ product.price }} руб<h2>
						<p>{{ product.description }}</p>
					</div>
				</a>
			</div>
{% endfor%}