adminapp/urls.py
from django.contrib import admin
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path(
        "users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="user_update"
    ),
    path(
        "users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="user_delete"
    ),
    path("categories/create/", adminapp.category_create, name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/", adminapp.category_update, name="category_update"
    ),
    path(
        "categories/delete/<int:pk>/", adminapp.category_delete, name="category_delete"
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="product_create",
    ),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path(
        "products/read/<int:pk>/",
        adminapp.ProductDetailView.as_view(),
        name="product_read",
    ),
    path(
        "products/update/<int:pk>/",
        adminapp.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/delete/<int:pk>/",
        adminapp.ProductDeleteView.as_view(),
        name="product_delete",
    ),
]

authapp/urls.py
from django.urls import path, re_path

from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("change_password/", views.change_password, name="change_password"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", views.verify, name="verify"
    ),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin_staff/", include("adminapp.urls", namespace="admin_staff")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include("ordersapp.urls", namespace="orders"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory


class ShopUserEditAdminForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ShopUserCreateAdminForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "email",
            "age",
            "avatar",
            "city",
            "phone",
        )


class AdminProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductCategoryAdminForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

adminapp/views/category.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from adminapp.forms import ProductCategoryAdminForm
from adminapp.utils import superuser_required
from mainapp.models import ProductCategory


@superuser_required
def categories(request):
    categories = ProductCategory.objects.all().order_by("id")

    return render(
        request,
        "adminapp/category/categories.html",
        context={
            "title": "Категории",
            "objects": categories,
        },
    )


@superuser_required
def category_create(request):
    if request.method == "POST":
        form = ProductCategoryAdminForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))
    else:
        form = ProductCategoryAdminForm()

    return render(
        request,
        "adminapp/category/edit.html",
        context={
            "title": "Создание категории",
            "form": form,
        },
    )


@superuser_required
def category_update(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        form = ProductCategoryAdminForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))
    else:
        form = ProductCategoryAdminForm(instance=category)

    return render(
        request,
        "adminapp/category/edit.html",
        context={
            "title": "Редактирование категории",
            "form": form,
        },
    )


@superuser_required
def category_delete(request, pk):
    title = "Удаление категории"

    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse("admin:categories"))

    content = {"title": title, "category_to_delete": category}

    return render(request, "adminapp/category/delete.html", content)

adminapp/views/product.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from adminapp.forms import AdminProductEditForm
from adminapp.utils import superuser_required
from mainapp.models import Product, ProductCategory


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/edit.html"
    fields = "__all__"

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            "category": self.get_category(),
        }

    def get_success_url(self):
        return reverse("adminapp:products", kwargs=self.kwargs)

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context


@superuser_required
def products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category).order_by("id")

    return render(
        request,
        "adminapp/product/products.html",
        context={
            "title": "Продукты",
            "category": category,
            "objects": products,
        },
    )


class ProductDetailView(DetailView):
    model = Product
    template_name = "adminapp/product/read.html"

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = AdminProductEditForm
    template_name = "adminapp/product/update.html"

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:products", args=[product_item.category_id])


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "adminapp/product/delete.html"

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:products", args=[product_item.category_id])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(
            reverse("adminapp:products", args=[self.object.category_id])
        )

adminapp/views/user.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from adminapp.forms import ShopUserCreateAdminForm, ShopUserEditAdminForm
from adminapp.utils import superuser_required
from authapp.models import ShopUser


class UserCreateView(CreateView):
    model = ShopUser
    template_name = "adminapp/user/edit.html"
    form_class = ShopUserCreateAdminForm
    success_url = reverse_lazy("admin:users")

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создание пользователя"
        return context


class UserListView(ListView):
    model = ShopUser
    template_name = "adminapp/user/users.html"
    paginate_by = 1

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Список пользователей"
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = "adminapp/user/edit.html"
    form_class = ShopUserEditAdminForm
    success_url = reverse_lazy("admin:users")

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Редактирование пользователя"
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = "adminapp/user/delete.html"
    success_url = reverse_lazy("admin:users")

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Удаление пользователя"
        return context

adminapp/templates/adminapp/product/delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить продукт <strong>{{ object.name }}</strong>?
    <form action="{% url 'admin:product_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
        <a href="{% url 'admin:product_read' object.category.pk %}" class="btn btn-success " role="button">
            отмена
        </a>
    </form>
    
</div>
{% endblock %}

adminapp/templates/adminapp/product/edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:products' category.pk %}">
      к списку категорий продуктов
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/product/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
		
    {% for object in objects %}
      <div class="product_record
        {% if not object.is_active %}
            not_active
        {% endif %}">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/product/read.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="product_read">
    <div class="product_name">
        Продукт <strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="summary">
        <b>цена</b>
        <p>{{ object.price }} руб</p>
        <b>количество</b>
        <p>{{ object.quantity }}</p>
        <b>в каталоге</b>
        <p>{% if object.is_active %}
                да
            {% else %}
            нет
            {% endif %}</p>
        <p>
            <button>
                <a href={% url 'admin:product_update' object.pk %}>редактировать</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'admin:product_delete' object.pk %}>удалить</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'admin:products' object.category.pk %}>назад</a>
            </button>
        </p>
    </div>
    <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p><br><br>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/product/update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'admin:products' object.category.pk %}" class="btn btn-outline-secondary btn-block my-3" role="button">
        к списку продуктов
    </a>
</div>
{% endblock %}