authapp/urls.py
from django.urls import path, re_path

from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("change_password/", views.change_password, name="change_password"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", views.verify, name="verify"
    ),
]

basketapp/urls.py
from django.urls import path

from . import views

app_name = "basketapp"

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id>/", views.add, name="add"),
    path("remove/<int:basket_item_id>/", views.remove, name="remove"),
    path("edit/<int:basket_item_id>/<int:quantity>/", views.edit, name="edit"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin_staff/", include("adminapp.urls", namespace="admin_staff")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include("ordersapp.urls", namespace="orders"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"

urlpatterns = [
    path("", views.products, name="all"),
    path("<int:category_id>", views.category, name="category"),
    path("<int:category_id>/<int:page>", views.category, name="paged_category"),
    path("product/<int:product_id>", views.product, name="product"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=100)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name="активна", default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя", max_length=100)
    price = models.DecimalField(
        verbose_name="цена", max_digits=7, decimal_places=2, default=0
    )
    color = models.TextField(verbose_name="цвет", blank=True)
    description = models.TextField(verbose_name="описание", blank=True)
    image = models.ImageField(verbose_name="картинка", blank=True, upload_to="products")
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)
    is_active = models.BooleanField(verbose_name="активен", default=True)

    def __str__(self):
        return self.name

adminapp/views/product.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from adminapp.forms import AdminProductEditForm
from adminapp.utils import superuser_required
from mainapp.models import Product, ProductCategory


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/edit.html"
    fields = "__all__"

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            "category": self.get_category(),
        }

    def get_success_url(self):
        return reverse("adminapp:products", kwargs=self.kwargs)

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context


@superuser_required
def products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category).order_by("id")

    return render(
        request,
        "adminapp/product/products.html",
        context={
            "title": "Продукты",
            "category": category,
            "objects": products,
        },
    )


class ProductDetailView(DetailView):
    model = Product
    template_name = "adminapp/product/read.html"

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = AdminProductEditForm
    template_name = "adminapp/product/update.html"

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:products", args=[product_item.category_id])


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "adminapp/product/delete.html"

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:products", args=[product_item.category_id])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(
            reverse("adminapp:products", args=[self.object.category_id])
        )

mainapp/views.py
import random

from django.core.paginator import EmptyPage, Paginator
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .models import Product, ProductCategory


def index(reqest):
    products = Product.objects.all()[:4]
    return render(
        reqest,
        "mainapp/index.html",
        context={
            "current_year": timezone.now().year,
            "title": "Главная",
            "products": products,
        },
    )


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def products(reqest):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product()
    return render(
        reqest,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "products": products.exclude(pk=hot_product.pk)[:4],
            "categories": categories,
            "hot_product": hot_product,
        },
    )


def category(reqest, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=category_id)
    products = Product.objects.filter(category=category)

    paginator = Paginator(products, 3)
    try:
        products_page = paginator.page(page)
    except:
        products_page = paginator.page(paginator.num_pages)

    return render(
        reqest,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "products": products_page,
            "paginator": paginator,
            "page": products_page,
            "categories": categories,
            "category": category,
            "hot_product": get_hot_product(),
        },
    )


def product(reqest, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(
        reqest,
        "mainapp/product.html",
        context={
            "title": "Продукты",
            "product": product,
            "categories": categories,
        },
    )


def contact(reqest):
    return render(
        reqest,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
        },
    )

mainapp/templates/mainapp/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">

    {% block header %}

    Здесь будет заголовок!

    {% endblock %}

    {% block content %}
    Здесь будет контент!
    {% endblock %}

    <div class="clr"></div>

</div>

<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now "Y" %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block header %}
<div class="hero">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block header %}
<div class="slider">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static "img/arrow.png" %}" alt=""></a>
	</div>	
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="featured">
	<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		{% include 'mainapp/includes/inc_products.html' %}
		</div>	
	</div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">
	{% include 'mainapp/includes/inc_categories_menu.html' %}

	{% if product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ product.image.url }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static "img/controll.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static "img/controll1.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static "img/controll2.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ product.price }} <span>руб</span></p>
			{% if user.is_authenticated %}
				<a href="{% url 'basket:add' product.id %}" class="red-button">
			{% else %}
				<a href="{% url 'auth:login' %}" class="red-button">
			{% endif %}
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ product.description|linebreaks }}
			</div>
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">

	{% include 'mainapp/includes/inc_categories_menu.html' %}

	{% if hot_product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ hot_product.name }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static "img/controll.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static "img/controll1.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static "img/controll2.jpg" %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ hot_product.price }} <span>руб</span></p>
			{% if user.is_authenticated %}
				<a href="{% url 'basket:add' hot_product.id %}" class="red-button">
			{% else %}
				<a href="{% url 'auth:login' %}" class="red-button">
			{% endif %}
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ hot_product.description|linebreaks }}
			</div>
		</div>
	</div>
	{% endif %}

	{% if products %}
	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% include 'mainapp/includes/inc_products.html' %}

		</div>
	</div>
	{% endif %}
</div>
{% endblock %}